### ISSUE TITLE
Re-run benchmark?

### ISSUE THREAD

**Issue by jpountz** [tantivy-search/tantivy-search.github.io#4]
Hello,

What would it take to update the website with results for a more recent version of Lucene? There have been improvements to Lucene lately, plus I suspect that the Lucene version that is used is actually Lucene 8.10 even though the website says it's 9.6. https://github.com/quickwit-oss/search-benchmark-game/blob/0ca432c568abbdf95f74e0d95c5652748fd0d6c7/engines/lucene-9.6.0/build.gradle#L15

In case you're curious, from local benchmarks Lucene is catching up but still a bit behind PISA and Tantivy on average.

I'm happy to run the benchmark myself if it helps, but then I would need help on getting a few things right:
 - hardware (AWS c7 instance? or maybe c5 in case Tantivy/PISA have a preference for Intel CPUs?),
 - OS,
 - Rust version (latest?),
 - Engines (Rust latest, Lucene latest, Lucene latest with BP, PISA?)

**Comment by fulmicoton** [comment]
Yes you can run it and share the JSON.
That would be great actually.

c7, some AWS Linux thing, 
Rust 1.75  should be great.
For Lucene, pick your weapon.
For PISA,... I have not been able to run the build of the index last time. Building PISA is quite annoying tbh. If you struggle too much you can ask them for help.

**Comment by jpountz** [comment]
@fulmicoton I opened a PR with updated results: https://github.com/tantivy-search/tantivy-search.github.io/pull/6.
